name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=2.2.2
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.13.2
      - protobuf==3.20.*