name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - pip:
      - wandb==0.13.3
      - protobuf
      - git+https://github.com/sebpadawan/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components

