name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=1.14.1
  - pip:
      - wandb==0.13.3
      - git+https://github.com/sebpadawan/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
